apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: auth-mongo-pv-claim
  namespace: hackerchat
spec: 
  accessModes: 
  - ReadWriteOnce
  storageClassName: nfs-storageclass
  resources: 
    requests: 
      storage: 100M
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: auth-mongo-depl
  namespace: hackerchat
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: auth-mongo
  template: 
    metadata: 
      labels: 
        app: auth-mongo
    spec: 
      containers: 
        - name: auth-mongo
          image: mongo
          volumeMounts: 
            - mountPath: "/data/db"
              name: auth-mongo-volume
      volumes: 
        - name: auth-mongo-volume
          persistentVolumeClaim: 
            claimName: auth-mongo-pv-claim
---
apiVersion: v1
kind: Service
metadata: 
  name: auth-mongo-cip
  namespace: hackerchat
spec: 
  selector: 
    app: auth-mongo
  type: ClusterIP
  ports: 
    - name: mongo
      protocol: TCP
      port: 27017
      targetPort: 27017